### ISSUE TITLE
Compatibility with Fedora 40

### ISSUE THREAD

**Issue by InToSSH** [bocekm/eobcanka-rpm#9]
Fedora 40 removed the openssl1.1 and there is no official package for F40. 
This causes the installation to fail.
The openssl1.1 needs to be downloaded from the F39 repo here: https://koji.fedoraproject.org/koji/buildinfo?buildID=2245678 and installed manually. It can coexist with the included openssl:3.2.1 so no need to remove it.

After installing the openssl1.1, the official install guide from README can be followed.
I tested with eObcanka-3.4.1 deb package and it is working correctly.

**Comment by bocekm** [comment]
Thanks, @InToSSH. The new eObcanka 3.4.2 package now expects openssl3.0 so the hassle with openssl1.1 is gone: https://github.com/bocekm/eobcanka-rpm/pull/10.
